export const cuisineType = [
	{ key: 1, value: "Italian" },
	{ key: 2, value: "French" },
	{ key: 3, value: "Chinese" },
	{ key: 4, value: "Indian" },
	{ key: 5, value: "Mexican" },
	{ key: 6, value: "Japanese" },
	{ key: 7, value: "Thai" },
	{ key: 8, value: "Korean" },
	{ key: 9, value: "Greek" },
	{ key: 10, value: "Spanish" },
	{ key: 11, value: "Vietnamese" },
	{ key: 12, value: "American" },
	{ key: 13, value: "Turkish" },
	{ key: 14, value: "Brazilian" },
	{ key: 15, value: "Lebanese" },
	{ key: 16, value: "Caribbean" },
	{ key: 17, value: "Ethiopian" },
	{ key: 18, value: "Moroccan" },
	{ key: 19, value: "Peruvian" },
	{ key: 20, value: "Cuban" },
	{ key: 21, value: "German" },
	{ key: 22, value: "Russian" },
	{ key: 23, value: "Australian" },
	{ key: 24, value: "Egyptian" },
	{ key: 25, value: "South African" },
	{ key: 26, value: "Argentinian" },
	{ key: 27, value: "Malaysian" },
	{ key: 28, value: "Filipino" },
	{ key: 29, value: "Portuguese" },
	{ key: 30, value: "Pakistani" },
	{ key: 31, value: "Polish" },
	{ key: 32, value: "Hungarian" },
	{ key: 33, value: "Persian" },
	{ key: 34, value: "Afghan" },
	{ key: 35, value: "Bangladeshi" },
	{ key: 36, value: "Nepalese" },
	{ key: 37, value: "Sri Lankan" },
	{ key: 38, value: "Indonesian" },
	{ key: 39, value: "Singaporean" },
	{ key: 40, value: "Belgian" },
	{ key: 41, value: "Swiss" },
	{ key: 42, value: "Austrian" },
	{ key: 43, value: "Scottish" },
	{ key: 44, value: "Irish" },
	{ key: 45, value: "Cajun" },
	{ key: 46, value: "Creole" },
	{ key: 47, value: "Hawaiian" },
	{ key: 48, value: "Middle Eastern" },
	{ key: 49, value: "Nordic" },
	{ key: 50, value: "Scandinavian" },
];
